config:
  partial_parse: false
  use_colors: true
  printer_width: 100
  send_anonymous_usage_stats: false

eba_dpm_profile:
  target: dev

  outputs:
    dev:
      type: bigquery
      method: oauth
      project: "{{ env_var('PROJECT_ID') }}"
      dataset: "{{ env_var('EBADPM_BQ_DEV') }}"
      threads: 10
      timeout_seconds: 300
      location: "{{ env_var('BQ_LOCATION') }}"
      priority: interactive
      retries: 1
