bigquery:
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: "{{ env_var('PROJECT_ID') }}"
      dataset: "{{ env_var('CREDIT_POC_BQ_DATA', 'credit_poc') }}"
      priority: interactive
      threads: 75
      job_execution_timeout_seconds: 30000
      location: "{{ env_var('BQ_LOCATION') }}"
      job_retries: 1
  target: dev
