steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', '${LOCATION}-docker.pkg.dev/$PROJECT_ID/reg-repo/cre-data_generator', '.' ]
images: [ '${LOCATION}-docker.pkg.dev/$PROJECT_ID/reg-repo/cre-data_generator' ]
