
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'sample_reporting'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'sample_regreporting_profile'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"

# Variables used in the SQL models
vars:
    reporting_day: '2021-09-01'      # The date when the report is valued at. Typically this would be today's date, and
                                     # should always be provided when the run command is issued, using the var flag - e.g.
                                     # dbt run --profiles-dir profiles --vars '{"reporting_day": "2021-09-03"}'

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
models:
  sample_reporting:
      # Storing the failures for all the tests
      +store_failures: true  # all tests
      # Config to store the columns descriptions in datacatalog
      +persist_docs:
          relation: true
          columns: true
      # Folder specific specs
      src:
          +tags: source
          materialized: ephemeral
      staging:
          +tags: staging
          materialized: table
      warehouse:
          +tags: warehouse
          materialized: incremental
      calc:
          +tags: calculations
          materialized: ephemeral
