steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-f', 'use_cases/examples/boe_cre/dbt/Dockerfile',
                   '--build-arg=BUILD_TAG=$TAG_NAME',
                   '--build-arg=BUILD_COMMIT=$COMMIT_SHA',
                   '-t', 'gcr.io/$PROJECT_ID/cre-dbt',
                   'use_cases/examples/boe_cre/dbt' ]
images: [ 'gcr.io/$PROJECT_ID/cre-dbt' ]
